data:
  n_drugs: 3
  min_dose_val: -6.0
  max_dose_val: 4.0
  drug_library: "../models/model_batchie/"
  control_samples: ["RPE", "BJ"]
  dose_agg: "min"

screenshot:
  model_path: "../models/model_batchie/final_model/"

mlp_finetuned:
  checkpoint: "../models/mlp_batchie/best_model.pt"
